exec-once = waybar -c /home/0xc4t/.config/waybar/mocha/config.jsonc -s /home/0xc4t/.config/waybar/mocha/style.css & swww-daemon
exec-once = swww img /home/0xc4t/.config/wallpaper/default.jpg --transition-fps 60 --transition-type any --transition-duration 3
exec-once = copyq --start-server
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = xrdb -merge ~/.Xresources
exec-once = swaync -s ~/.config/swaync/style.css
exec-once = eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
exec-once = /home/0xc4t/.local/bin/hyprland.sh
exec-once = vicinae server
exec-once =  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-L1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
