exec-once = waybar -c $HOME/.config/waybar/nerd/config.jsonc -s $HOME/.config/waybar/nerd/style.css & swww-daemon
exec-once = swww img $HOME/.config/wallpaper/favorit/nier.png --transition-fps 60 --transition-type any --transition-duration 3
exec-once = copyq --start-server
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = xrdb -merge ~/.Xresources
exec-once = swaync -s ~/.config/swaync/style.css
exec-once = eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
exec-once = $HOME/.local/bin/hyprland.sh
exec-once = vicinae server
