#####################
### LOOK AND FEEL ###
#####################
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(b4befeaa)
    #col.active_border = rgba(cdd6f4aa)
    # col.active_border = rgba(cdd6f4aa) rgb(b4befe) 45deg
    col.inactive_border = rgb(2a273f)
    # resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    rounding_power = 2

    blur {
        enabled = yes
        size = 10
        # passes = 4
        new_optimizations = on
        ignore_opacity = on
        noise = 0.01
        contrast = 0.8
        vibrancy = 0.2
   }
}


dwindle {
     pseudotile = true
     preserve_split = true
}

master {
    new_status = master
}


misc {
    vrr = 0
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    animate_manual_resizes = false
    disable_splash_rendering = false
    vfr = true
}


xwayland {
    force_zero_scaling = true
}

scrolling {
    column_width = 0.7
    fullscreen_on_one_column = true
    follow_min_visible = 0.1
    focus_fit_method = 0
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0
    focus_fit_method = 1
    follow_focus = true
}
