monitor=eDP-1,1920x1200@60.0,316x1440,1.0
monitor=DP-1,2560x1440@180.0,0x0,1.0

bindl=,switch:off:Lid Switch,exec,~/.config/hypr/scripts/clamshell.sh open
bindl=,switch:on:Lid Switch,exec,~/.config/hypr/scripts/clamshell.sh close
