# Includes
include colors.conf

# Fonts
font_family      Iosevka Nerd Font
font_size        14
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# Window Config
background_opacity      0.95
hide_window_decorations yes
window_padding_width    5
window_margin_width     5
confirm_os_window_close 0
window_border_width 1pt

# Cursor Config
cursor_shape      beam
cursor_trail      5
cursor_text_color #000000

# Tab Bar Settings
tab_bar_edge              bottom
tab_bar_style             separator
tab_separator             " "
tab_title_template        "[{title}]"
active_tab_title_template "[{title}]"
active_tab_font_style     bold
inactive_tab_font_style   normal

# Terminal Bell
enable_audio_bell no

# Key Bindings
map ctrl+shift+n set_tab_title
map ctrl+enter new_tab
map ctrl+q     close_tab
map ctrl+l     clear_terminal scroll active
map alt+1 first_window
map alt+2 second_window
map alt+3 third_window
map alt+4 fourth_window
map alt+5 fifth_window
map alt+6 sixth_window
map alt+7 seventh_window
map alt+8 eighth_window
map alt+9 ninth_window
map alt+0 tenth_window
map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
